### ISSUE TITLE
Slideshow for Presentation

### ISSUE THREAD

**Issue by n-aggarwal** [n-aggarwal/privacy-messaging-app#20]
We need to develop a slideshow for our presentation:

The main topics from my point of view are:
API Security
End-to-End Encryption
No Screenshot functionality
Blocking photos from other devices (Theoretical)
Deleting Messages

Feel free to add more stuff by commenting below.

**Comment by a-jacewicz** [comment]
Slideshow is complete! Everyone should make sure they know what they're going to say in class today! Link to it: https://docs.google.com/presentation/d/1PkJLAopBvjOEjUAWPg7yRgU5Mszu3NIFK7UC6lcQgLY/edit?usp=sharing
